app/routes/auth_views.py
from flask import render_template, Blueprint

bp = Blueprint("auth_views", __name__)

@bp.route('/sign_up')
def sign_up():
    return render_template('sign_up.html')


@bp.route('/login')
def login():
    print("Login view")
    return render_template('login.html')

app/routes/home_view.py
from flask import Flask, render_template, redirect, url_for, Blueprint, session

bp = Blueprint("home_view", __name__)

@bp.route("/home")
def home():
   if "username" in session:
      user = session
      return render_template("home.html", user=user)
   else:
      return render_template('index.html')

app/routes/hydricfp_view.py
from flask import Blueprint, render_template, redirect, url_for, session

bp = Blueprint("hydricfp_views", __name__)

@bp.route('/hydricfp')
def hydricfp():
    if 'username' in session:
        user = session
        return render_template('hf_products.html', user=user)
    else:
       return redirect(url_for('indexes_views.index_views'))

app/templates/carbonfp_energy.html
{%extends '/layouts/base.html' %} {% block title %} Electric calculator {% endblock %} {%block navbar%}
<button
  type="button"
  class="flex mx-3 cursor-pointer text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600 hover:scale-105 hover:transition-transform"
  id="user-menu-button"
  aria-expanded="false"
  data-dropdown-toggle="dropdown">
  <span class="sr-only">Open user menu</span>
  <img class="w-8 h-8 rounded-full" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/michael-gough.png" alt="user photo" />
</button>
<!-- Dropdown menu -->
<div class="hidden z-50 my-4 w-56 text-base list-none bg-white divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 rounded-xl" id="dropdown">
  <div class="py-3 px-4">
    <span class="block text-sm font-semibold text-gray-900 dark:text-white">{{ user["username"] }}</span>
    <span class="block text-sm text-gray-900 truncate dark:text-white">{{ user["email"] }}</span>
  </div>
  <ul class="py-1 text-gray-700 dark:text-gray-300" aria-labelledby="dropdown">
    <li>
      <a href="#" class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">My profile</a>
    </li>
    <li>
      <a href="#" class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">Account settings</a>
    </li>
  </ul>
  <ul class="py-1 text-gray-700 dark:text-gray-300" aria-labelledby="dropdown">
    <li>
      <a href="#" class="flex items-center py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
        ><svg class="mr-2 w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd"></path>
        </svg>
        My likes</a
      >
    </li>
    <li>
      <a href="#" class="flex items-center py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
        ><svg class="mr-2 w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z"></path>
        </svg>
        Collections</a
      >
    </li>
    <li>
      <a href="#" class="flex justify-between items-center py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
        <span class="flex items-center">
          <svg aria-hidden="true" class="mr-2 w-5 h-5 text-primary-600 dark:text-primary-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path
              fill-rule="evenodd"
              d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z"
              clip-rule="evenodd"></path>
          </svg>
          Pro version
        </span>
        <svg aria-hidden="true" class="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
        </svg>
      </a>
    </li>
  </ul>
  <ul class="py-1 text-gray-700 dark:text-gray-300" aria-labelledby="dropdown">
    <li>
      <a href="#" class="logout block pt-2 pb-1 px-4 text-sm text-red-500 hover:bg-gray-100 dark:hover:bg-gray-600 rounded-b-lg">Log out</a>
    </li>
  </ul>
</div>
{%endblock%} {% block sidebar %}
<a href="" class="logout flex items-center p-2 gap-2 text-base font-medium text-gray-900 rounded-lg transition duration-75 hover:bg-gray-100 dark:hover:bg-gray-700 dark:text-red-500 group">
  <i class="fa-solid fa-right-to-bracket w-6 h-6 text-xl text-center pt-1"></i>
  <span class="">Log out</span>
</a>
{% endblock %} {%block main%}
<div class="flex justify-center items-center min-h-screen p-4">
  <div id="container" class="h-fit w-fit items-center px-4 py-8 text-black dark:text-white bg-gray-50 dark:bg-gray-900 rounded-lg">
    <section id="container" class="mx-auto space-y-8">
      <header class="flex items-center justify-center text-center gap-3">
        <i class="fa-solid fa-bolt text-4xl sm:text-5xl"></i>
        <h1 class="text-3xl sm:text-5xl font-bold">Electricity Calculator</h1>
      </header>

      <div class="p-4 space-y-6">
        <div class="flex flex-row justify-center items-center gap-4">
          <button
            id="btnBasic"
            class="text-white bg-[#238c80] hover:bg-[#1f756e] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-4 py-2 text-center hover:scale-105 transition"
            onclick="show_form('basic_calculation')">
            Basic Calculator
          </button>
          <button
            id="btnAccurate"
            class="text-white bg-[#238c80] hover:bg-[#1f756e] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-4 py-2 text-center hover:scale-105 transition"
            onclick="show_form('accurate_calculation')">
            Accurate Calculator
          </button>
        </div>

        <div id="basic_calculation" class="form mt-6" hidden>
          <form class="space-y-6">
            <header class="flex items-center justify-center gap-3 bg-[#9696a3] rounded-2xl p-3">
              <i class="fa-solid fa-plug"></i>
              <h2 class="text-2xl">Basic Calculation</h2>
            </header>

            <input type="hidden" name="type_calculation" value="basic_calculation" />

            <section>
              <label for="electricity_consumption" class="block mb-2 text-lg font-medium"> How much electricity was consumed during the week? </label>
              <input type="number" name="electricity_consumption" id="electricity_consumption" placeholder="Kw" min="1" class="w-full p-2 text-black bg-[#9696a3] rounded shadow" required />
            </section>

            <footer class="text-center">
              <button
                type="submit"
                class="text-white bg-[#238c80] hover:bg-[#1f756e] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center hover:scale-105 transition">
                Continue
              </button>
            </footer>
          </form>
        </div>

        <div id="accurate_calculation" class="form mt-6 bg-gray-100 dark:bg-gray-900 p-4" hidden>
          <form id="devices_select_form" class="space-y-6">
            <header class="flex items-center justify-center gap-3 bg-[#9696a3] rounded-2xl p-3">
              <i class="fa-solid fa-bolt"></i>
              <h2 class="text-2xl">Accurate Calculation</h2>
            </header>

            <p class="text-base text-center">Select the devices you use in your home, then click 'Continue'.</p>

            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {% set zones = ['Kitchen', 'Living Room', 'Bedroom', 'Office / Study Room', 'Bathroom', 'Laundry Room', 'Mobile and portable devices', 'Others'] %} {% for zone in zones %}
              <section class="bg-gray-200 dark:bg-gray-800 p-4 rounded-lg">
                <header class="mb-4 flex gap-2 items-center">
                  <i
                    class="fa-solid {% if zone == 'Kitchen' %}fa-kitchen-set {% elif zone == 'Living Room' %}fa-couch {% elif zone == 'Bedroom' %}fa-bed {% elif zone == 'Office / Study Room' %}fa-briefcase {% elif zone == 'Bathroom' %}fa-bath {% elif zone == 'Laundry Room' %}fa-washing-machine {% elif zone == 'Mobile and portable devices' %}fa-mobile {% else %}fa-plug{% endif %}"></i>
                  <h3 class="text-lg font-semibold">{{ zone }}</h3>
                </header>
                <div class="space-y-2">
                  {% for device in devices %} {% if device.deviceZone == zone %}
                  <!-- <label class="flex items-center gap-2">
                    <input type="checkbox" name="selected_devices" value="{{ device.id }}" class="device-checkbox w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded" />
                    <span class="text-sm font-medium">{{ device.deviceName }}</span>
                  </label> -->
                  <div class="device-wrapper">
                    <div class="flex items-center mb-2">
                      <input type="checkbox" name="selected_devices" value="{{ device.id }}" class="device-checkbox w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded" />
                      <label class="ms-2 text-sm font-medium">{{ device.deviceName }}</label>
                    </div>
                  </div>
                  {% endif %} {% endfor %}
                </div>
              </section>
              {% endfor %}
            </div>

            <footer class="text-center space-x-4">
              <button
                id="continue-btn"
                type="button"
                class="text-white bg-[#238c80] hover:bg-[#1f756e] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 hover:scale-105 transition">
                Continue
              </button>
              <button
                id="calculate-btn"
                type="submit"
                class="hidden text-white bg-[#238c80] hover:bg-[#1f756e] focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 hover:scale-105 transition">
                Calculate Carbon Footprint
              </button>
            </footer>
          </form>
        </div>
      </div>
    </section>
  </div>
</div>

{%endblock%} {%block scripts%}
<script src="{{ url_for('static', filename='javascript/carbonfp-energy.js') }}"></script>
{%endblock%}

app/templates/home.html
{%extends 'layouts/base.html' %} {%block title%}Cleanlyfe{%endblock%} {%block navbar%}
<button
  type="button"
  class="flex mx-3 cursor-pointer text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600 hover:scale-105 hover:transition-transform"
  id="user-menu-button"
  aria-expanded="false"
  data-dropdown-toggle="dropdown">
  <span class="sr-only">Open user menu</span>
  <img class="w-8 h-8 rounded-full" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/michael-gough.png" alt="user photo" />
</button>
<!-- Dropdown menu -->
<div class="hidden z-50 my-4 w-56 text-base list-none bg-white divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 rounded-xl" id="dropdown">
  <div class="py-3 px-4">
    <span class="block text-sm font-semibold text-gray-900 dark:text-white">{{ user["username"] }}</span>
    <span class="block text-sm text-gray-900 truncate dark:text-white">{{ user["email"] }}</span>
  </div>
  <ul class="py-1 text-gray-700 dark:text-gray-300" aria-labelledby="dropdown">
    <li>
      <a href="#" class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">My profile</a>
    </li>
    <li>
      <a href="#" class="block py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">Account settings</a>
    </li>
  </ul>
  <ul class="py-1 text-gray-700 dark:text-gray-300" aria-labelledby="dropdown">
    <li>
      <a href="#" class="flex items-center py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
        ><svg class="mr-2 w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd"></path>
        </svg>
        My likes</a
      >
    </li>
    <li>
      <a href="#" class="flex items-center py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
        ><svg class="mr-2 w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z"></path>
        </svg>
        Collections</a
      >
    </li>
    <li>
      <a href="#" class="flex justify-between items-center py-2 px-4 text-sm hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
        <span class="flex items-center">
          <svg aria-hidden="true" class="mr-2 w-5 h-5 text-primary-600 dark:text-primary-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path
              fill-rule="evenodd"
              d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z"
              clip-rule="evenodd"></path>
          </svg>
          Pro version
        </span>
        <svg aria-hidden="true" class="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
        </svg>
      </a>
    </li>
  </ul>
  <ul class="py-1 text-gray-700 dark:text-gray-300" aria-labelledby="dropdown">
    <li>
      <a href="#" class="logout block pt-2 pb-1 px-4 text-sm text-red-500 hover:bg-gray-100 dark:hover:bg-gray-600 rounded-b-lg">Log out</a>
    </li>
  </ul>
</div>
{%endblock%} {% block sidebar %}
<a href="" class="logout flex items-center p-2 gap-2 text-base font-medium text-gray-900 rounded-lg transition duration-75 hover:bg-gray-100 dark:hover:bg-gray-700 dark:text-red-500 group">
  <i class="fa-solid fa-right-to-bracket w-6 h-6 text-xl text-center pt-1"></i>
  <span class="">Log out</span>
</a>
{% endblock %} {%block main%}
<section class="">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0 text-black dark:text-white">
    <div class="flex space-x-4">
      <button class="text-white bg-[#20b9a7] hover:bg-[#20b9a7] ring-2 ring-[#20b9a7] text-xl text-center rounded-3xl px-2 py-2 font-bold hover:scale-105 hover:transition-transform">
        <a href="/carbonfp/transport">Go transport footprint</a>
      </button>
      <button class="text-white bg-[#20b9a7] hover:bg-[#20b9a7] ring-2 ring-[#20b9a7] text-xl text-center rounded-3xl px-2 py-2 font-bold hover:scale-105 hover:transition-transform">
        <a href="{{ url_for('hydricfp_views.hydricfp') }}">Go hidric footprint</a>
      </button>
    </div>
  </div>
</section>
{%endblock%} {%block scripts%}
<script src="{{ url_for('static', filename='javascript/authentication.js') }}"></script>
{%endblock%}

app/templates/index.html
{%extends 'layouts/base.html' %} {%block title%}Cleanlyfe{%endblock%} {% block navbar %}
  
<div class="gap-4 hidden sm:flex">
  
  <a href="{{ url_for('auth_views.login') }}">
    <button
      type="button"
      class="text-white bg-green-500 hover:bg-green-800 hover:scale-105 transition-transform duration-300 focus:outline-none focus:ring-4 focus:ring-green-300 font-bold rounded-full text-sm px-5 py-2 text-center dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800 cursor-pointer">
      Log in
    </button>
  </a>
  
  <a href="{{ url_for('auth_views.sign_up') }}">
    <button
      type="button"
      class="border focus:outline-none hover:scale-105 transition-transform duration-300 focus:ring-4 font-bold rounded-full text-sm px-5 py-2 bg-gray-800 text-white border-gray-600 hover:bg-gray-700 hover:border-gray-600 focus:ring-gray-700 cursor-pointer">
      Sign up
    </button>
  </a>
</div>

{% endblock %} {%block main%}
<section id="container" class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0 gap-6">
  <img class="size-32" src="{{ url_for('static', filename='img/favicon.ico') }}" alt="" />

  <div>
    <h1 class="text-5xl bg-gradient-to-r from-green-500 to-sky-500 bg-clip-text font-extrabold text-transparent text-center py-3">Welcome to Cleanlyfe, transform your habits, save the planet</h1>
  </div>

  <div class="px-3">
    <p class="text-2xl text-black mt-4 text-center dark:text-white">
      Cleanlyfe analyzes your lifestyle to help you understand the impact you have on the environment through dynamic surveys, we collect information about your energy consumption, transportation,
      food and more. We then show you your ecological footprint in interactive, visual dashboards, where you can explore each category, discover patterns and make more sustainable decisions based on
      your own data.
    </p>
  </div>
</section>

{%endblock%}

app/templates/index_worldmatters.html
{%extends 'layouts/base_wm.html' %} {% block title %} WorldMatters {% endblock %} {% block navbar %}

<div class="gap-4 hidden sm:flex">
  <!-- BOTON LOG IN -->
  <a href="{{ url_for('auth_views.login') }}">
    <button
      type="button"
      class="text-white bg-green-500 hover:bg-green-800 hover:scale-105 transition-transform duration-300 focus:outline-none focus:ring-4 focus:ring-green-300 font-bold rounded-full text-sm px-5 py-2 text-center dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800 cursor-pointer">
      Log in
    </button>
  </a>
  <!-- BOTON SING UP -->
  <a href="{{ url_for('auth_views.sign_up') }}">
    <button
      type="button"
      class="border focus:outline-none hover:scale-105 transition-transform duration-300 focus:ring-4 font-bold rounded-full text-sm px-5 py-2 bg-gray-800 text-white border-gray-600 hover:bg-gray-700 hover:border-gray-600 focus:ring-gray-700 cursor-pointer">
      Sign up
    </button>
  </a>
</div>

{% endblock %} {%block main%}

<div class="px-4 py-4">
  <!-- Imagen de portada -->
  <header class="w-full mb-8">
    <img src="../static/img/portada_worldmatters.webp" alt="Our products" class="w-full h-48 sm:h-56 md:h-64 lg:h-80 xl:h-96 2xl:h-[28rem] object-cover rounded-lg shadow-lg" />
  </header>

  <section class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <!-- Título de la sección -->
    <h1 class="text-3xl font-bold text-center mb-6" id="title">Nuestros productos</h1>
    <!-- Descripción de la sección -->
    <p class="text-center text-xl mb-8 text-balance px-2 sm:px-10" id="text">
      En WorldMatters, ofrecemos una variedad de productos diseñados para mejorar tu bienestar y el del planeta. Con aplicaciones para monitoriar la huella de carbono que generas y un producto que te
      ayuda a cuidar el agua mediante un llave remota.
    </p>
  </section>

  <div class="grid grid-cols-1 md:grid-cols-2 max-w-3xl mx-auto py-6 place-items-center gap-12">
    <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow-lg hover:scale-105 transition-transform duration-300">
      <a href="/home">
        <img class="rounded-t-lg" src="../static/img/CleanLyfe.webp" alt="CleanLyfe" />
      </a>
      <div class="p-5">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-black">CleanLyfe</h5>
        <p class="mb-3 font-normal text-black text-balance">CleanLyfe es una aplicacion que ayuda a gestionar mejor la huella de carbono de cada uno y ver todas las estadisticas.</p>
        <a
          href="/home"
          class="inline-flex items-center px-3 py-2 text-sm font-medium text-cente text-white bg-green-600 rounded-lg hover:bg-green-700 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-700 hover:scale-105 transition-transform duration-300">
          Read more
          <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9" />
          </svg>
        </a>
      </div>
    </div>
    <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow-lg hover:scale-105 transition-transform duration-300">
      <a href="/waterflow">
        <img class="rounded-t-lg" src="../static/img/WaterFlow.webp" alt="CleanLyfe" />
      </a>
      <div class="p-5">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-black">WaterFlow</h5>
        <p class="mb-3 font-normal text-black text-balance">Es un producto que se puede cerrar de manera remota por medio de una aplicacion web o movil.</p>
        <a
          href="/waterflow"
          class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-green-600 rounded-lg hover:bg-green-700 focus:ring-4 focus:outline-none focus:ring-green-700 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-700 hover:scale-105 transition-transform duration-300">
          Read more
          <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9" />
          </svg>
        </a>
      </div>
    </div>
  </div>
</div>
{%endblock%}